[package]
name = "pscan"
version = "0.1.0"
edition = "2021"
description = "A port scanner"
license = "Unlicense"

[dependencies]
clap = {version = "4.5.26", features = ["derive"]}
once_cell = "1.20.2"
